name: SAP Icomp's Deploy

on:
  push:
    branches: [develop, test, main]
    paths:
      - "backend/**"
      - "docker/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
    runs-on: ubuntu-latest

    env:
      APP_ENV: ${{ vars.APP_ENV }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t sap-icomp-backend-$APP_ENV:latest -f ./backend/Dockerfile.$APP_ENV .

      - name: Export image to tar.gz
        run: |
          docker save sap-icomp-backend-$APP_ENV:latest | gzip > sap-icomp-backend-$APP_ENV.tar.gz

      - name: Generate .env file for the backend
        run: |
          cat <<EOF > .env
          ENVIRONMENT="$APP_ENV"
          BACKEND_PORT="${{ vars.BACKEND_PORT }}"
          DB_PORT="${{ vars.DB_PORT }}"
          DB_NAME="${{ secrets.DB_NAME }}"
          DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          DB_USER="${{ secrets.DB_USER }}"
          DB_HOST="${{ secrets.SERVER_HOST }}"
          EOF

      - name: Copy image, compose and env to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "sap-icomp-backend-${{ env.APP_ENV }}.tar.gz,./docker/${{ env.APP_ENV }}/docker-compose.yml,.env"
          target: "/var/www/${{ secrets.HOST_MAIN_FOLDER }}"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/${{ secrets.SERVER_USER }}/sapicomp
            chmod 600 .env

            docker load < sap-icomp-backend-$APP_ENV.tar.gz

            docker compose -f docker-compose.yml -p sap-icomp-$APP_ENV up -d db backend

            rm -f sap-icomp-backend-$APP_ENV.tar.gz
            docker image prune -f
