FROM node:22-alpine

RUN apk add --no-cache openssl
WORKDIR /app

# Copy dependencies and install
COPY package*.json ./
COPY ./prisma ./prisma
RUN npm install

# Copy the code and generate the Prisma Client
COPY . .

# Run the development script with hot-reloading and database deployment
CMD ["sh", "-c", "npm run db:deploy && npm run dev"]