FROM node:22-alpine

RUN apk add --no-cache openssl
WORKDIR /app

# Copy dependencies and install
COPY package*.json ./
COPY ./prisma ./prisma
RUN npm install

# Copy the code
COPY . .

# Define the variable to development environment
ENV NODE_ENV=test

# Run the development script with hot-reloading
CMD ["sh", "-c", "npm run db:deploy && npm run prisma:seed:prod && npm start"]