services:
  db:
    image: postgres:17-alpine
    container_name: sap-icomp-postgres-database-production
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_dataproduction:/var/lib/postgresql/data

  backend:
    image: sap-icomp-backend-production:latest
    container_name: sap-icomp-backend-production
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db

  frontend:
    image: sap-icomp-frontend-production:latest
    container_name: sap-icomp-frontend-production
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend

volumes:
  postgres_dataproduction:
