export enum AppointmentStatusEnum {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELED_BY_STUDENT = "CANCELED_BY_STUDENT",
  CANCELED_BY_PEDAGOGUE = "CANCELED_BY_PEDAGOGUE",
  EXPIRED = "EXPIRED",
  COMPLETED = "COMPLETED",
  MISSED = "MISSED",
}
