services:
  db:
    image: postgres:17-alpine
    container_name: sap-icomp-postgres-database-develop
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_datadevelop:/var/lib/postgresql/data

  backend:
    image: sap-icomp-backend-develop:latest
    container_name: sap-icomp-backend-develop
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db

  frontend:
    image: sap-icomp-frontend-develop:latest
    container_name: sap-icomp-frontend-develop
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

volumes:
  postgres_datadevelop:
